### ISSUE TITLE
Conflict with dependency

### ISSUE THREAD

**Issue by Medy111** [igdb/api-android-java#3]
I just tried the API wrapper for android . I followed the Setup and get the following error when I snyched gradle files for the first time.

Error:Execution failed for task ':app:preDebugAndroidTestBuild'.
> Conflict with dependency 'com.android.support.test:runner' in project ':app'. Resolved versions for app (0.5) and test app (1.0.1) differ. See https://d.android.com/r/tools/test-apk-dependency-conflicts.html for details.

How do I fix this ?

Im Using the lastest version of Android studio.

**Comment by Medy111** [comment]
I tried to fix this by changing the testrunner  from "testImplemation" to "implemtation" ... which stopped the error ... though Im not sure if that fixed the issue since -->

Then I tried one of the Gametest samples methods.
- I put in ym Api Key
- copied the sample method inisde my main activity
- ran testSingleGames(); inside oncreate to see if it works.
--> app crash....


package testigdb.testigdb;

import android.content.Context;
import android.support.test.InstrumentationRegistry;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.android.volley.VolleyError;
import com.igdb.api_android_java.callback.onSuccessCallback;
import com.igdb.api_android_java.model.APIWrapper;
import com.igdb.api_android_java.model.Parameters;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import static junit.framework.Assert.assertEquals;
import static junit.framework.Assert.fail;

public class MainActivity extends AppCompatActivity {


    private Context context;
    private APIWrapper wrapper;




    public void setUp() throws InterruptedException {
        context = InstrumentationRegistry.getContext();
        String key = System.getProperty("90608a365bde4f14c80a710e2e5c2e85");
        wrapper = new APIWrapper(context, key);

    }

    @Test
    public void testSingleGames() throws InterruptedException {
        setUp();
        Parameters parameters = new Parameters()
                .addIds("1942");

        final CountDownLatch lock = new CountDownLatch(1);
        wrapper.games(parameters, new onSuccessCallback() {
            @Override
            public void onSuccess(JSONArray result) {
                try {
                    lock.countDown();
                    JSONObject object = result.getJSONObject(0); // index 0 = first result
                    int testId = object.getInt("id");   // testId output is what we will use for our App
                    assertEquals(1942, testId);


                    Log.d("Firsttest","JSON" + result.toString());

                } catch (JSONException e) {
                    e.printStackTrace();
                    fail("JSONException!!");
                }


            }

            @Override
            public void onError(VolleyError error) {
                fail("Volley Error!!");
            }
        });
        lock.await(20000, TimeUnit.MILLISECONDS);

    }


    **@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {
            testSingleGames();
        } catch (InterruptedException e) {
            e.printStackTrace();**
        }

    }
}

**Comment by husnjak** [comment]
Hello I have looked into your issue and i believe that i have solved it. 
the Link: https://d.android.com/r/tools/test-apk-dependency-conflicts.html states that there is a dependency conflict in this wrapper and your project, so i updated the dependencies in the wrapper to the latest for the new version for Android Studio 3.0 

try this new gradle dependecy: 
compile 'com.github.igdb:api-android-java:1.1'

**Comment by Medy111** [comment]
```
package testigdb.testigdb;

import android.content.Context;
import android.support.test.InstrumentationRegistry;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.android.volley.VolleyError;
import com.igdb.api_android_java.callback.onSuccessCallback;
import com.igdb.api_android_java.model.APIWrapper;
import com.igdb.api_android_java.model.Parameters;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import static junit.framework.Assert.assertEquals;
import static junit.framework.Assert.fail;

public class MainActivity extends AppCompatActivity {


    private Context context;
    private APIWrapper wrapper;




    public void setUp() throws InterruptedException {
        context = InstrumentationRegistry.getContext();
        String key = System.getProperty("90608a365bde4f14c80a710e2e5c2e85");
        wrapper = new APIWrapper(context, key);

    }

    @Test
    public void testSingleGames() throws InterruptedException {
        setUp();
        Parameters parameters = new Parameters()
                .addIds("1942");

        final CountDownLatch lock = new CountDownLatch(1);
        wrapper.games(parameters, new onSuccessCallback() {
            @Override
            public void onSuccess(JSONArray result) {
                try {
                    lock.countDown();
                    JSONObject object = result.getJSONObject(0); // index 0 = first result
                    int testId = object.getInt("id");   // testId output is what we will use for our App
                    assertEquals(1942, testId);


                    Log.d("Firsttest","JSON" + result.toString());

                } catch (JSONException e) {
                    e.printStackTrace();
                    fail("JSONException!!");
                }


            }

            @Override
            public void onError(VolleyError error) {
                fail("Volley Error!!");
            }
        });
        lock.await(20000, TimeUnit.MILLISECONDS);

    }


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {
            testSingleGames();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
}

```

This is the task I run in main acticvity .. I still get the same Exception.

java.lang.RuntimeException: Unable to start activity ComponentInfo{testigdb.testigdb/testigdb.testigdb.MainActivity}: java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.

**Comment by husnjak** [comment]
So you are trying to run one of the test in your main activity?

If you just want to get a response from the server i would advice you to use one of the examples:

```java
APIWrapper wrapper = new APIWrapper(context, "YOUR_API_KEY");
Parameters params = new Parameters()
	.addFields("*")
	.addorder("published_at:desc");
	
wrapper.games(params, new onSuccessCallback(){
	@Override
        public void onSuccess(JSONArray result) {
        	// Do something with resulting JSONArray
        }

        @Override
        public void onError(VolleyError error) {
            // Do something on error
        }
});

/* The sent request will look like this:
https://api-2445582011268.apicast.io/games/?fields=*&order=published_at:desc */
```

The tests are designed to work without a context, which you already have, and that is why we use 
InstrumentationRegistry and CountDownLatch. You don't need this for responses.

Also, You might want to change your API key as it is now public on the internet..

**Comment by Medy111** [comment]
Yes I just wanted to run one of the test methods and get a response.
As I said im not too familiar with apis & learning atm.

with the example you provided im running into the same issue .


```
package testigdb.testigdb;

import android.content.Context;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

import com.android.volley.VolleyError;
import com.igdb.api_android_java.callback.onSuccessCallback;
import com.igdb.api_android_java.model.APIWrapper;
import com.igdb.api_android_java.model.Parameters;

import org.json.JSONArray;


public class MainActivity extends AppCompatActivity {

    private Context context;

    APIWrapper wrapper = new APIWrapper(context, "I_put_key_here");

    public void dostuff()throws InterruptedException{

        Parameters params = new Parameters()
                .addFields("*")
                .addOrder("published_at:desc");

        wrapper.games(params, new onSuccessCallback(){
            @Override
            public void onSuccess(JSONArray result) {
                Log.d("test","test" + result.toString());
            }

            @Override
            public void onError(VolleyError error) {
                Log.d("test","test");
            }
        });

    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {
            dostuff();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
}

```

**Comment by husnjak** [comment]
hmm, 

Try this: 

```java
APIWrapper wrapper = new APIWrapper(getApplicationContext(), "API_KEY");

        Parameters params = new Parameters()
                .addFields("*")
                .addOrder("published_at:desc");

        wrapper.games(params, new onSuccessCallback(){
            @Override
            public void onSuccess(JSONArray result) {
                // Do something with resulting JSONArray
                Log.d("tesst", "result: " + result.toString());
            }

            @Override
            public void onError(VolleyError error) {
                Log.e("tesst", "error: " + error);
            }
        });
````

Are you running this on your own phone or emulator?

**Comment by Medy111** [comment]
It worked
I run on emulator.

**Comment by husnjak** [comment]
great!

**Comment by Medy111** [comment]
I still cant comprehend what is going on here :D ... but im glad it works now.

**Comment by Medy111** [comment]
Another Issue : Im unable to call the same dostuff method from another class -->
`
java.lang.RuntimeException: Unable to start activity ComponentInfo{testigdb.testigdb/testigdb.testigdb.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference``


What I want is to call dostuff2(); from another Class inside my Oncreate Method in my MainActivity.

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        SampleResponse method = new SampleResponse();
        method.dostuff2();   // call from SampleResponse Class


    }
}
```


This is the method -->

```
APIWrapper wrapper;
    public void dostuff2() {
        wrapper = new APIWrapper(getApplicationContext(), "api key");
        Parameters params = new Parameters()
                .addFields("*")
                .addOrder("published_at:desc");

        wrapper.games(params, new onSuccessCallback() {
            @Override
            public void onSuccess(JSONArray result) {
                Log.d("test", "test" + result.toString());
            }

            @Override
            public void onError(VolleyError error) {
                Log.d("test", "test");
            }
        });

    }

}
```
`


Can you explain what is going on here ? From the error I could see that it it somehow related to the .Context.getApplicationContext() method which gave me trouble in the first place.

Previously -->

When I pasted the offical sample into my project-->
**Parameters** & **.addorder** couldnt be resolved

--> I imported parameters from your libary which solved that , but
--> context couldnt be resolved , so I added Context context;
--> .addorder still couldnt be resolved ?
--> by adding getApplicationContext() you solved this , though now I can call this method from another class ?


```
Context context; // added this

        APIWrapper wrapper = new APIWrapper(context, "api key");
        Parameters params = new Parameters()  // -->
 // imported import   com.igdb.api_android_java.model.Parameters;

                .addFields("*")
                .addorder("published_at:desc"); // cant be resolved

        wrapper.games(params, new onSuccessCallback() {
            @Override
            public void onSuccess(JSONArray result) {
                // Do something with resulting JSONArray
                Log.d("test", "test");
            }

            @Override
            public void onError(VolleyError error) {
                // Do something on error
            }
        });

    }
```

**Comment by Medy111** [comment]
Can you help me figure out why I have to use:

`        APIWrapper wrapper = new APIWrapper(getApplicationContext(), "API_KEY");`

instead of

`    APIWrapper wrapper = new APIWrapper(context, ""API_KEY");`

**Comment by Medy111** [comment]
Never mind. First world noob Problems . I learned some more about Context Class and solved it :D.

This was helpful 👍 
https://itekblog.com/android-context-in-non-activity-class/

Im good to go now ;).
