### ISSUE TITLE
update readme to reflect "implementation"

### ISSUE THREAD

**Issue by TomQDRS** [igdb/api-android-java#7]
This is a very minor issue, but the readme should be updated to reflect that in the project dependencies, "compile" is deprecated and is going to be removed by the end of 2018. "implementation" should be used instead for buildtime improvements, see https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration?utm_source=android-studio#new_configurations

**Comment by husnjak** [comment]
nice! Thank you. The docs have been updated with implementation instead of compile.
